#!/usr/bin/env python3
# Builds public/theme.css from the dark-mode rules below.
# Each rule is written twice: once for "Dark" chosen on the switch
# (:root[data-theme="dark"]) and once for "Same as my phone" when the phone is
# dark (@media prefers-color-scheme: dark, unless "Light" was chosen).
# Run:  python3 helpers/build-theme-css.py
import os, re
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "theme-dark.css")
ALL = os.path.join(HERE, "theme-all.css")
OUT = os.path.join(HERE, "..", "public", "theme.css")
src = open(SRC, encoding="utf-8").read()
src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
rules = re.findall(r"([^{}]+)\{([^{}]*)\}", src)
def scoped(prefix, sel):
    out = []
    for s in sel.split(","):
        s = s.strip()
        if not s: continue
        out.append(prefix if s == ":root" else prefix + " " + s)
    return ",\n".join(out)
dark, auto = [], []
for sel, body in rules:
    body = " ".join(body.split())
    dark.append(scoped(':root[data-theme="dark"]', sel) + " { " + body + " }")
    auto.append("  " + scoped(':root:not([data-theme="light"])', sel).replace("\n", "\n  ") + " { " + body + " }")
head = """/* GrievIQ light/dark display for citizens and representatives (Oct 2026).
   GENERATED by helpers/build-theme-css.py from helpers/theme-dark.css -- edit those, not this.
   Light is each page's own colours. Dark: dark grey (not black), softer colours,
   WCAG 2.2 AA contrast (4.5:1 text, 3:1 controls). Photos and maps unchanged. */
:root { color-scheme: light; }
:root[data-theme="dark"] { color-scheme: dark; }
@media print { :root[data-theme="dark"] { color-scheme: light; } }
@media screen and (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { color-scheme: dark; } }
"""
both = open(ALL, encoding="utf-8").read()
open(OUT, "w", encoding="utf-8").write(head + both + "\n/* Dark is for screens only: printing always uses the light colours. */\n@media screen {\n" + "\n".join(dark) + "\n}\n@media screen and (prefers-color-scheme: dark) {\n" + "\n".join(auto) + "\n}\n")
print("wrote", OUT, len(rules), "rules")
